/*
 * generated by Xtext 2.23.0
 */
package marsRover.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MrDslUiModule extends AbstractMrDslUiModule {

	public MrDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
