/*
 * generated by Xtext 2.23.0
 */
package marsRover.validation;

import org.eclipse.xtext.validation.Check;

import marsRover.mrDsl.BackwardForMove;
import marsRover.mrDsl.DistanceConditionBackGT;
import marsRover.mrDsl.DistanceConditionBackLT;
import marsRover.mrDsl.DistanceConditionFrontGT;
import marsRover.mrDsl.DistanceConditionFrontLT;
import marsRover.mrDsl.ForwardForMove;
import marsRover.mrDsl.LeftForMove;
import marsRover.mrDsl.RightForMove;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MrDslValidator extends AbstractMrDslValidator {
	
	@Check
	void checkDegreesLeft(LeftForMove move) {
		int degrees = move.getDegrees();
		if(degrees < 0 | degrees > 360) 
			error("Degrees must be between 0 and 360", null);
	}
	
	@Check
	void checkDegreesRight(RightForMove move) {
		int degrees = move.getDegrees();
		if(degrees < 0 | degrees > 360) 
			error("Degrees must be between 0 and 360", null);
	}
	
	@Check
	void checkRotationsForward(ForwardForMove move) {
		int rotations = move.getDistance();
		if(rotations < 0) 
			error("Rotations must be more than 0", null);
	}
	
	@Check
	void checkRotationsBackward(BackwardForMove move) {
		int rotations = move.getDistance();
		if(rotations < 0) 
			error("Rotations must be more than 0", null);
	}

	@Check
	void checkDistanceFrontLT(DistanceConditionFrontLT condition) {
		int distance = condition.getDistance();
		if(distance < 0) 
			error("Distance must be positive", null);
	}

	@Check
	void checkDistanceFrontGT(DistanceConditionFrontGT condition) {
		int distance = condition.getDistance();
		if(distance < 0) 
			error("Distance must be positive", null);
	}
	
	@Check
	void checkDistanceBackLT(DistanceConditionBackLT condition) {
		int distance = condition.getDistance();
		if(distance < 0) 
			error("Distance must be positive", null);
	}
	
	@Check
	void checkDistanceBackGT(DistanceConditionBackGT condition) {
		int distance = condition.getDistance();
		if(distance < 0) 
			error("Distance must be positive", null);
	}
}
